### ISSUE TITLE
Varrock Sewers still not working

### ISSUE THREAD

**Issue by AidenEsco** [daxmagex/Runescape-Web-Walker-Engine#2]
When trying to pass the web in varrock sewers it will walk right up to the web then give this error and stop the script 
`[12:18:11] java.lang.NullPointerException
[12:18:11] 	at scripts.Mine.Shared.webwalker_logic.local.walker_engine.interaction_handling.f.g(PathObjectHandler.java:211)
[12:18:11] 	at scripts.Mine.Shared.webwalker_logic.local.walker_engine.interaction_handling.f.g(PathObjectHandler.java:181)
[12:18:11] 	at scripts.Mine.Shared.webwalker_logic.local.walker_engine.j.g(WalkerEngine.java:145)
[12:18:11] 	at scripts.Mine.Shared.webwalker_logic.h.g(WebWalker.java:128)
[12:18:11] 	at scripts.Mine.AIOABCL2.F(AIOABCL2.java:7837)
[12:18:11] 	at scripts.Mine.AIOABCL2.run(AIOABCL2.java:2151)
[12:18:11] 	at java.lang.Thread.run(Thread.java:745)
[12:18:11] Runtime: 00 H 04 M 19 S`
Using Tri AIO combat and magic if that makes a difference, i believe its running 1.1.13

**Comment by daxmagex** [comment]
I'll check it out.
